// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlCBhA52Og-yW3T7WOT9SnkcF5Tqdet8',
    appId: '1:960088574839:web:568b2304f688ab87522f72',
    messagingSenderId: '960088574839',
    projectId: 'chat-de58d',
    authDomain: 'chat-de58d.firebaseapp.com',
    storageBucket: 'chat-de58d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpXZFH_Rkejo3Sfeevu8avQv-qUlcl6Q',
    appId: '1:960088574839:android:642735f0a368d0e5522f72',
    messagingSenderId: '960088574839',
    projectId: 'chat-de58d',
    storageBucket: 'chat-de58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotjwxcwDGYogtSqU04EoYF3_ITJKhxqA',
    appId: '1:960088574839:ios:7d0f68d846453668522f72',
    messagingSenderId: '960088574839',
    projectId: 'chat-de58d',
    storageBucket: 'chat-de58d.appspot.com',
    iosBundleId: 'com.example.thirdStep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotjwxcwDGYogtSqU04EoYF3_ITJKhxqA',
    appId: '1:960088574839:ios:0f8c77e367734630522f72',
    messagingSenderId: '960088574839',
    projectId: 'chat-de58d',
    storageBucket: 'chat-de58d.appspot.com',
    iosBundleId: 'com.example.thirdStep.RunnerTests',
  );
}
